sudo: required
dist: trusty

language: cpp

compiler:
 - gcc

before_script:
 - export curr_path=$PWD
 - cd ..
 - svn co https://oceanai.mit.edu/svn/moos-ivp-aro/releases/moos-ivp-15.5 moos-ivp
 - cd moos-ivp
 - sudo apt-get update -q
 - sudo apt-get install -y --force-yes g++ subversion xterm cmake libfltk1.3-dev freeglut3-dev libpng12-dev libjpeg-dev libxft-dev libxinerama-dev libtiff4-dev tree
 - ./build-moos.sh -j $((`nproc` / 2))
 - ./build-ivp.sh -m -f -j $((`nproc` / 2))
 - export PATH=$PATH:$PWD/bin
 - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
 - cd "$curr_path"

script:
 - ./GenMOOSDriver.sh Driver "MOOS Dev."
 - ./build.sh -j $((`nproc` / 2))
 - tree